export const testimonials = [
    {
        "testimonial": "Ever since I was very young I wanted to open up a bakery. I have always enjoyed baking, and friends and family have told me for a long time they and others would be happy to pay for a batch of my fresh cookies. But being a baker does not suddenly make you a good business person. Thankfully, I brought the few ideas I had to BIGbigger, and they helped fill in the blanks. I am now living my dream of doing what I love and supporting myself and family with it."
    },
    {
        "testimonial": "I have always been the idea starter, but never the finisher. When I was young I opened up a lemonade stand with my friends, and we had a lot of fun doing it! The problem was we never planned out how much lemonade actually costs to make, and did not set the price accordingly. Now as an adult, on a much larger scale, I have tons of great ideas with lots of holes in them. With BIGbigger, I came with my great ideas, and the gaps were filled in by experienced individuals, ready to make my dreams come true!"
    },
    {
        "testimonial": "You know that feeling when you have a great idea, you write it down to make sure you don't forget, and you get really excited by just how awesome it is? And then a week later, you find the note, and laugh to yourself because you realize how unfinished your thoughts were. I've got notebooks FULL of ideas. Thanks to BIGbigger, I've seen some of those ideas actually come to life, and make me money! I couldn't have accomplished what I have without the help BIGbigger has given me."
    },
    {
        "testimonial": "BIGbigger delivered on every expectation I had! They were kind, professional, and truly interested in my ideas and invested in my success. From the first meeting I had with the BIGbigger team, I knew I was in good hands. They listened to me, clearly communicated their ideas, and laid out a realistic, step by step plan to help me prioritize everything I needed to do. They provided the catalyst I needed to actually realize my business concept, and now I’m living my dream! Without BIGbigger, I can honestly say I never would have gotten past the daydream stage."
    },
    {
        "testimonial": "When I first reached out to BIGbigger, I wasn’t entirely sure what to expect. I’d read the reviews, I’d explored the website, but I was still a little nervous about sharing my ideas. Were they good enough? Were they ready to share? I shouldn’t have worried. BIGbigger was enthusiastic from the get-go and the whole team got my vision. They helped flesh out the details and got me to where I am now. Special shoutout to Heather, who went the extra mile to make sure I was involved at every stage of the process!"
    },
    {
        "testimonial": "BIGbigger saved my business! I’m an old dog who struggles to learn new tricks. My business was slowing, and I knew I needed to change my business model if I was going to keep my livelihood. I was referred to BIGbigger by another business owner at our local chamber of commerce luncheon, and I called them the same day. The BIGbigger representative I spoke to was eager to help, and I soon realized how well equipped the entire team was. They helped me adapt my practices and business approach, helped me expand my online presence, and my business is now stronger than it ever was."
    },
    {
        "testimonial": "Hiring a think tank seemed like such a big step, but I will never regret it! I had an idea, made an appointment at BIGbigger, and I walked out of that room with a grin on my face and the confidence that my dream was going to come true. Having a whole team behind me and my idea was empowering, and I’ve learned so many great skills along the way. How to prioritize and think through every angle of an issue, and the importance of teamwork. Amazing things happen at BIGbigger, and I will definitely recommend them to anyone looking for an incredible team!"
    },
    {
        "testimonial": "I’m the mayor of a small town in Colorado, and I knew there were so many improvements I could make in our town. But with limited staff, I knew I needed some help with the details. I’m so grateful my girlfriend knew about BIGbigger and that she made me make that first call. The staff at BIGbigger were excited to help work on policies that would actually work to fulfill the vision I had for my town. They were especially good at helping me refine my environmental policies. The entire town loves the adopted policies and our home is cleaner, happier, and more inclusive."
    },
    {
        "testimonial": "I’ve always been incredibly handy. When there was something to be put together or fixed around the house, I was the person my parents and siblings would come to. I love fixing things and building things. I especially love being able to help people build and fix things. Recently, my sister suggested that I could make a living off my passion, and I fell in love with the idea. But I quickly realized that I didn’t know the first thing about starting a business. Luckily, a friend referred me to BIGbigger, who devoted a team to taking my dream and making it a reality. Now, I’m living that dream, and loving every second!"
    },
    {
        "testimonial": "To swipe up or to swipe down? That is the question. I always hear people complaining about dating apps. They’re too expensive, they’re too impersonal, they keep cycling through the same pool of potentials. As someone who tied the knot before dating apps were even a thought, I’ve always said that an app can never replace real human meetings. But then I got to thinking: What if there was a dating app that could actually mimic that first interaction? I became fixated on the idea, but I didn’t know where to even start. But BIGbigger made it so easy. Their team was knowledgeable, professional, and so great to work with. And now, there is a dating app worth using!"
    },
    {
        "testimonial": "My passion has always revolved around clothing. I love sewing, I love designing, and I love creating clothes that are unique and beautiful. I’ve always said, if I could just make a living doing what I love, all my dreams would come true. But it didn’t seem realistic to even dream about being able to quit my “real” job and pursue my dream--until I found BIGbigger. They helped me figure it all out! The details, the structure, the logistics. They thought of everything, and now I can live the life I always wanted, and make the world a more beautiful place, one stitch at a time!"
    },
    {
        "testimonial": "There is nothing more amazing than the human body. I think we can all agree on that. And taking proper care of our bodies is more than worth the time and effort. But it’s one thing to say it, and it’s another thing to live it. I worked for years as a personal trainer, and while I loved my job, I always felt like there had to be a better way to help my clients--and everyone--to make healthy living a lifestyle. I brought my thoughts and ideals to BIGbigger, and they took it for a run! It was amazing to see my desperate hope become something attainable. Now, thanks to the amazing team at BIGbigger, I can help people live better and love it"
    },
    {
        "testimonial": "Art is a language all its own. Art can communicate things mere words never could. Ideas, emotions, history. Ever since I received my first art kit for my third birthday, I have loved art of all kinds, and the magic it overflows with. I’ve always wished I could make enough money to live on, just by being an artist, but it always seemed like a ridiculous goal. But the amazing people at BIGbigger helped me to realize that not only is it possible, but totally realistic and achievable! They helped me to develop a plan and work through all the details, and I couldn’t be more satisfied with their work. So, if you have a dream that seems out of reach, take it to BIGbigger, and they will build you a ladder."
    },
    {
        "testimonial": "Love, love, love! That’s how I feel about BIGbigger and their wonderful team of brilliant experts. I brought them a half-baked idea, and what did they do? They turned it into a reality! I was blown away by the efficient and effective way they took my scraps of an idea and created a viable business model! Every single person I interacted with was friendly, knowledgeable, and just as excited about my dream as I was! I am telling everyone I know about BIGbigger, and I’m telling you too: No matter what your dream or idea is, no matter how vague or miniscule, take it to BIGbigger and let them work their magic. You won’t be disappointed!"
    },
    {
        "testimonial": "As someone who was raised in a bilingual household, I’ve always valued communication. I studied language, literature, and speech in college, and got a job as a translator. I loved what I did, but I also came to realize that translation services are expensive, and many people and small businesses who need the service can’t afford it, and have to do without. I believe everyone should be able to make themselves heard and understood, so I started my crusade. I brought my ideas to BIGbigger and they helped me work out the kinks and create a functional business plan. Now, thanks to BIGbigger, we’re bringing a voice to the world."
    },
    {
        "testimonial": "It’s a small world after all. We all know the song, but we don’t all get to realize the fact. Traveling the world is expensive and can seem like an unattainable dream. As an army brat, I travelled all over the world and always thought it wasn’t fair that so many people never get the chance. I wanted to make the world small for everyone and enable them to explore it. And BIGbigger made that possible. With their knowledgeable and experienced team, we put our heads together and now I run a travel agency designed for anyone who has ever had a dream to see the world."
    },
    {
        "testimonial": "Cleanliness is close to godliness, as the saying goes. I have always loved cleaning and organizing, and many studies have shown that having a clean space to live and work in improves health, productivity, and satisfaction. After high school, I tried for a couple years to start my own cleaning business, but could never get it to take off. I shelved that dream, and figured I would never dust it off, but then I found BIGbigger. They helped me pull my failed business out of storage and give it a total makeover. Now I have the business I always wanted, and it’s thanks to the incredible team as BIGbigger."
    },
    {
        "testimonial": "Growing up, when I was asked what I wanted to do when I grew up, I always told people that I wanted to run a hotel. When I was in high school, I decided I actually wanted to run a bed and breakfast instead. But there was so much to figure out, I didn’t have the first clue how to even start. I had pretty much given up my dream when I found BIGbigger. They helped me figure out all the details and develop a functional business model. Now I run a bed and breakfast and it is everything I always dreamed it could be. A special thank you to Kimberly who was there with me during every step of my journey."
    }
]